common/urls.py
from django.urls import path
from .import views
app_name = 'common'
urlpatterns = [
    path('',views.home, name='home'),
    path('reg',views.reg,name='register'),
    path('sign',views.sign, name='signin')
]

poster/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('uhome/',include('userhome.urls'))
]

userhome/urls.py
from django.urls import path
from .import views
app_name='userhome'


urlpatterns = [
    path('home',views.home, name='home'),
    path('prof',views.prof, name='profile'),
    path('logout/',views.log_out, name='logout'),
    path('edit/<int:u_id>',views.edit,name='edit'),
    path('update',views.update,name='update')
]   

common/models.py
from django.db import models
from distutils.command.upload import upload
from unittest.util import _MAX_LENGTH

# Create your models here.

class users(models.Model):
    name = models.CharField(max_length = 15)
    uname = models.CharField(max_length = 10)
    password = models.CharField(max_length = 10)

userhome/models.py
from django.db import models
from common.models import users
from unittest.util import _MAX_LENGTH

# Create your models here.

class post(models.Model):
    User = models.ForeignKey(users,on_delete = models.SET_NULL, null = True)
    u_title = models.CharField(max_length = 30)
    u_dis = models.CharField(max_length = 100)

common/views.py
from django.shortcuts import render,redirect
from . models import users


# Create your views here.

def home(request):
    
    return render (request,'common/home.html')

def reg(request):
    msg=''
    if request.method == 'POST':
        name = request.POST['fname']
        uname = request.POST['u_name']
        psw = request.POST['psw']
        user = users(name = name,uname = uname,password = psw)
        user.save()
        msg='account create successfully'
        return render (request,'common/signin.html',{'success':msg})
    return render (request,'common/register.html')

def sign(request):
    msg=''
    if request.method == 'POST':
        username = request.POST['u_name']
        userpass = request.POST['pass']

        try:
            userlogin = users.objects.get(uname = username,password = userpass)
            request.session['user_id'] = userlogin.id
            return redirect("userhome:home")
        except:
            msg = 'invalid username or password'
    return render (request,'common/signin.html',{'error':msg})

userhome/views.py
from django.shortcuts import render,redirect
from common.models import users
from .models import post

# Create your views here.
def home(request):
    posts = post.objects.all()
    user = users.objects.get(id = request.session['user_id'])
    if request.method =='GET':
        status = False
    if request.method == 'POST':
        if 'posting' in request.POST:
            title = request.POST['title']
            disc = request.POST['disc']
            upost = post(u_title = title,u_dis = disc,User_id=request.session['user_id'])
            upost.save() 
            
    return render (request,'userhome/home.html',{'post_data':posts,'user_data':user})

def prof(request):
    user = users.objects.get(id = request.session['user_id'])
    return render (request,'userhome/profile.html',{'user_data':user})

def log_out(request):
    del request.session ['user_id']
    request.session.flush()
    return redirect('common:home')

def edit(request,u_id):
    user = users.objects.get(id=u_id)
    return render(request,'userhome/edit.html',{'use':user})

def update(request):    
    if request.method == 'POST':
        print('haaaao')
        name = request.POST['n_ame']
        uname = request.POST['u_name']
        pas = request.POST['pas']
        userObj = users.objects.get(id=request.session['user_id']) 
        userObj.name = name
        userObj.uname = uname
        userObj.password = pas       
        # user = users(name=name,uname=uname,password=pas)
        # user.save()
        userObj.save()
      
    return redirect( 'userhome:profile')

common/templates/common/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="mainbody">
        <img src="{% static 'image/bg.jpg' %}" alt="">
        <a href="{% url 'common:register' %}"><input type="button" value="register"></a>
    </div>
</body>
</html>

common/templates/common/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/reg.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"
        integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>Document</title>
</head>

<body>
    <div class="main-box">
        <div class="form-cont">

            <div class="top-buttons">
                <button class="to-signup top-active-button">
                    Sign Up
                </button>
                <a href="{% url 'common:signin' %}"><button class="to-signin">
                        Sign In
                    </button></a>
            </div>

            <div class="form form-signup">
                <form method="post">
                    {% csrf_token %}
                    <div>
                        <lable>FULL NAME*</lable>
                        <input type="text" placeholder="Your full name" id="f_name" name="fname">
                        <span id="error1"></span>
                    </div>
                    <div>
                        <lable>User Name*</lable>
                        <input type="text" placeholder="Your Username" id="uname" name="u_name">
                        <span id="error2"></span><br>
                        <span id="error3">required, 10 charecters or fewer,special charecters,capital letter.</span>
                    </div>
                    <div>
                        <lable>PASSWORD*</lable>
                        <input type="password" placeholder="Your password" id="psw" name="psw"
                            pattern="(?=.*[a-z])(?=.*[A-Z]).{8,}"
                            title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters"
                            required><br>
                        <span id="inverror"></span><br>
                        <div id="message">
                            <p id="error4" class="invalid">Lowercase Letter</p><br>
                            <p id="error5" class="invalid">Uppercase Letter</p><br>
                            <p id="error6" class="invalid">A Number</p><br>
                            <p id="error7" class="invalid">10 charecters or fewer</p><br>
                        </div>
                    </div>
                    <input onclick="return validate()" type="submit" class="form-btn" value="Sign Up" />
                    <br><br>

                    <a href="#" class="lined-link to-signin-link">I'm already member</a><br><br>

                </form>
            </div>
        </div>
        <div class="clear-fix"></div>
    </div>
    <script>
        // $(document).ready(function(){
        //     $.ajaxSetup({
        //         headers:{
        //             "X-CSRFToken": $('[csrfmiddlewaretoken]').val()
        //         }
        //     })
        // })
    </script>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

common/templates/common/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/reg.css' %}">
    <title>Document</title>
</head>

<body>
    <div class="main-box">
        
        <div class="form-cont">
            <div class="suc">{{success}}</div>
            

            <div class="top-buttons">
                <a href="{% url 'common:register' %}"><button class="to-signup ">
                    Sign Up
                </button></a>
                <button class="to-signin top-active-button">
                    Sign In
                </button>
            </div>
            <div class="form form-signin">
                
                <form method="post">
                    {% csrf_token %}
                    <lable>User Name*</lable>
                    <input type="text" placeholder="Your User-name" name="u_name">
                    <lable>PASSWORD*</lable>
                    <input type="password" placeholder="Your password" name="pass">
                    <input type="submit" class="form-btn" value="Sign In" />
                    <br><br>
                    <a href="#" class="lined-link to-signup-link">Create new account</a><br><br>
                    <span style="color: red;">{{error}}</span><br><br>
                    
                </form>
            </div>
        </div>
        <div class="clear-fix"></div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

userhome/templates/userhome/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/basestyle.css' %}">
    <title>Document</title>
</head>

<body>
    <nav>
        <div class="wel">Profile</div>
        <div class="butt">
            <a href="{% url 'userhome:home' %}"><button>home</button></a>
            <a href="{% url 'userhome:logout' %}"><button>LogOut</button></a>
        </div>
    </nav>
    <section class="container1">
        <div class="container2">
            <div class="user-detailes">
                <div class="input-box">
                    <img src="{% static 'image/school2.jpg' %}" alt="">
                </div>
                <form  method="POST" action="{% url 'userhome:update' %}">
                    {% csrf_token %}
                    <div class="input-box">
                        <span class="detailes">Full Name &nbsp;:</span>
                        <input type="text" name="n_ame" value="{{use.name}}">
                    </div>
                    <div class="input-box">
                        <span class="detailes">User Name :</span>
                        <input type="text" name="u_name" value="{{use.uname}}">
                    </div>
                    <div class="input-box">
                        <span class="detailes">Password &nbsp;&nbsp; :</span>
                        <input type="text" name="pas" value="{{use.password}}">
                    </div>

                    <div class="input-box">
                        <button type="submit">update</button>
                    </div>
                </form>
            </div>
        </div>
    </section>

</body>

</html>

userhome/templates/userhome/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/basestyle.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <title>Document</title>
</head>

<body>
    <nav>
        <div class="wel">Welcome {{user_data.name}}</div>
        <div class="butt">
            <a href="{% url 'userhome:profile' %}"><button>profile</button></a>
            <a href="{% url 'userhome:logout' %}"><button>LogOut</button></a>
        </div>
    </nav>
    <div class="pop">
        <button type="button" class="btn btn-primary pe-4 ps-4 pt-3 pb-3" data-bs-toggle="modal"
            data-bs-target="#staticBackdrop">
            post
        </button>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form  method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <span>Title</span><br>
                        <input type="text" name="title" required><br>
                        <span>Discription</span><br>
                        <textarea id="dis" cols="60" rows="5" name="disc" required></textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" name="posting" class="btn btn-primary">post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    <div class="posts">
        {% for posts in post_data %}
        <div class="card" style="width: 34rem;">
            <div class="card-body">
                <h5 class="card-title">{{posts.u_title}}</h5><br>
                <p class="card-text">{{posts.u_dis}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js""></script>
</body>

</html>

userhome/templates/userhome/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/basestyle.css' %}">
    <title>Document</title>
</head>

<body>
    <nav>
        <div class="wel">Profile</div>
        <div class="butt">
            <a href="{% url 'userhome:home' %}"><button>home</button></a>
            <a href="{% url 'userhome:logout' %}"><button>LogOut</button></a>
        </div>
    </nav>
    <section class="container1">
        <div class="container2">
            <div class="user-detailes">
                <div class="input-box">
                    <img src="{% static 'image/school2.jpg' %}" alt="">
                </div>
                
                <div class="input-box">
                    <span class="detailes">Full Name &nbsp;:</span>
                    <div class="u_detailes">{{user_data.name}}</div>
                </div>
                <div class="input-box">
                    <span class="detailes">User Name :</span>
                    <div class="u_detailes">{{user_data.uname}}</div>
                </div>
                <div class="input-box">
                    <span class="detailes">Password &nbsp;&nbsp; :</span>
                    <div class="u_detailes">{{user_data.password}}</div>
                </div>
                
                <div class="input-box">
                    <a href="{% url 'userhome:edit' user_data.id %}"><button>Edit</button></a>
                </div>
            </div>
        </div>
    </section>

</body>

</html>